### ISSUE TITLE
Cannot fine Template Files on Validation

### ISSUE THREAD

**Issue by jmconnell2000** [tomaustin700/YAML-Pipeline-Validator-VS-Code-Extension#16] opened 2021-07-20 15:23 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Example yaml
A small yaml sample that can dulpicat the issue

**Additional context**

**Comment by jmconnell2000** [comment] 2021-07-20 15:27
While attempting to validate YAML on my local files (CTRL+ALT+V) I get the following error:
Can not find /Pipelines/webapi-deploy-preprod-job-template.yml

![image](https://user-images.githubusercontent.com/12616824/126351311-2b82022e-544f-487d-8699-a7a73f62ecf9.png)

I think the extension assumes all templates are found under a path called /Pipelines under the root.  All of my pipeline files are located on the root of my repo.

**Comment by tomaustin700** [comment] 2021-07-21 09:19
Hi @jmconnell2000, templates are not currently supported and this is a known issue and I'm not sure if it can be resolved at the moment. I'll update this as a known issue in the readme. Sorry about that,

**Comment by tomaustin700** [comment] 2021-07-21 09:20
Duplicate of #11

**Closed as completed by tomaustin700** 2021-07-21 09:20 UTC
